---
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=vfamim
      - POSTGRES_PASSWORD=poli2103
      - POSTGRES_DB=ny_taxy
    volumes:
      - "./data/external/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
